# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Texture Maker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SYFlatButton'
  

  # Pods for Texture Maker

  target 'Texture MakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Texture MakerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
